-- This is an empty migration.
-- CreateTriggerFunction
-- CREATE OR REPLACE FUNCTION set_trigger()
--     RETURNS trigger
--     LANGUAGE 'plpgsql'
-- AS 
-- $BODY$
-- BEGIN
-- 	UPDATE "Address" SET "isDefault" = false WHERE "isDefault" = true AND "user_id" = NEW."user_id";
--   RETURN NEW;
-- END;
-- $BODY$;

-- CreateTrigger
-- CREATE TRIGGER trigger_default_address
--     BEFORE INSERT OR UPDATE
--     ON public."Address"
--     FOR EACH ROW
--     WHEN (new."isDefault" = true)
--     EXECUTE FUNCTION public.set_trigger();